spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:blogger}
spring.datasource.username: postgres
spring.datasource.password: postgres
spring.jpa.hibernate.ddl-auto: update
