version: '3'
services:
  blogger-db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres4all
      POSTGRES_USER: blogger
      POSTGRES_DB: blogger
    volumes:
    - blogger-db-data:/var/lib/postgresql/data/

volumes:
  blogger-db-data:
